buildrunner:
	dart run build_runner build --delete-conflicting-outputs

lint:
	dart format .

test.dart:
	flutter test

clean_and_get:
	flutter clean
	flutter pub get

update_icon:
	dart run flutter_launcher_icons