name: tile_tally
description: An app to help you keep track of your Scrabble game.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flex_color_scheme: ^7.3.1
  uuid: ^4.3.3
  logger: ^2.2.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.3
  accessibility_tools: ^1.0.1
  fl_chart: ^0.67.0
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  feedback: ^3.1.0
  flutter_email_sender: ^6.0.3
  file_selector: ^1.0.3
  purchases_flutter: ^6.29.3
  http: ^1.2.1
  flutter_secure_storage: ^4.2.1
  mockito: ^5.4.4
  flutter_markdown: ^0.7.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  lints: ^3.0.0
  sqflite_common_ffi: any
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/board-game.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/txt/
    - assets/fonts/
    - assets/icon/
    - assets/md/

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: W95FA
      fonts:
        - asset: assets/fonts/W95FA/W95FA.otf
