runserver:
		python manage.py runserver

makemigrations:
		python manage.py makemigrations

makesuperuser:
		python manage.py createsuperuser

migrate:
		python manage.py migrate

shell:
		python manage.py shell

test:
		python manage.py test