# Generated by Django 5.0.6 on 2024-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchases',
            field=models.ManyToManyField(blank=True, to='accounts.purchase'),
        ),
    ]
