# Generated by Django 5.0.6 on 2024-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gameplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
