# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pub" # Or your package manager
    directory: "/" # Location of the package manifests
    schedule:
      interval: "weekly" # Or your preferred schedule
    target-branch: "main" # Or your default branch
    open-pull-requests-limit: 10 # Adjust as needed
    groups:
      - group-name: "all-dependencies" # Custom name for the group
        patterns:
          - "*" # This pattern aims to match all dependencies
